# Generated by Django 6.0 on 2025-12-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_university_material_permissionrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='core.course')),
            ],
            options={
                'ordering': ['year_number'],
                'unique_together': {('course', 'year_number')},
            },
        ),
    ]
